### ISSUE TITLE
Add ability to answer/decline a call

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/home-assistant-hikconnect#22]
As suggested by @pergolafabio:
- https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535/1142?u=tomasbedrich
- https://github.com/tomasbedrich/home-assistant-hikconnect/issues/20#issuecomment-1021218537

Decline (`cmdId=3`) verified as working even on my old device.

**Comment by pergolafabio** [comment]
yes, i'm using now a zigbee sensor at my door, so when door opens, all calls are dropping ! Verry usefull, android clinets stop ringing and also indoor stations... verry usefull if you just open door manually or with HA app :-)

anyway

cmd3 = reject call!
cmd2 = answer call
cmd5 = hangup

i use  a a combinaion in script, i fire first 2 and then 5
you could do 3 also, but then you have a hangup sound

also, i now disabled hikconnect push call, so now i open Hikconnect manually with action from HA push notification, and i start twaoway audio manually, then you also need to first answer/hangup call, otherwise the twoway audio is already in use

the reject call , then the visitor always haves a reject notification at doorstation, thats not convenient

**Comment by tomasbedrich** [comment]
Partially implemented in #39, no plans to implement other commands at the moment.

In case someone wants to implement also `cmd2` or `cmd5`, please use following PRs as an example:
- https://github.com/tomasbedrich/hikconnect/pull/12
- https://github.com/tomasbedrich/home-assistant-hikconnect/pull/39
